#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXAMPLE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RUN_DIR="$EXAMPLE_DIR/.run"
STATE_FILE="$RUN_DIR/session.env"
LOCALNET_DIR="$RUN_DIR/localnet"
SERVE_ADDR="127.0.0.1:8080"
SERVE_URL="http://$SERVE_ADDR"
VITE_ADDR="127.0.0.1:5173"
VITE_URL="http://$VITE_ADDR"
WORKSPACE_SHAKER_MANIFEST="$EXAMPLE_DIR/../../../toolchain/shaker/Cargo.toml"

LOCALNET_PID=""
SERVE_PID=""
VITE_PID=""
LYQUID_ID=""
MODE=""
SHAKER=()

usage() {
    cat <<'EOF'
Usage: scripts/run.sh [--hosted|--dev|--console|status|stop [--clean] [--force]|clean --artifacts]

Without an argument, choose a run mode interactively.
  --hosted  Build, deploy, and open the hosted production UI.
  --dev     Deploy, then start the Vite development UI with live reload.
  --console Build, deploy, and open the Shaker console.
  status    Show the current local Price Feed session.
  stop      Stop the recorded local session. --clean removes .run afterwards.
  clean     Remove ignored Price Feed build artifacts with --artifacts.
EOF
}

resolve_shaker() {
    if shaker inspect --help >/dev/null 2>&1; then
        SHAKER=(shaker)
    elif [[ -f "$WORKSPACE_SHAKER_MANIFEST" ]]; then
        SHAKER=(cargo run --quiet --manifest-path "$WORKSPACE_SHAKER_MANIFEST" --)
    else
        echo "Price Feed requires a Shaker version with the inspect command." >&2
        exit 1
    fi
}

write_state() {
    mkdir -p "$RUN_DIR"
    {
        printf 'LOCALNET_PID=%q\n' "$LOCALNET_PID"
        printf 'SERVE_PID=%q\n' "$SERVE_PID"
        printf 'VITE_PID=%q\n' "$VITE_PID"
        printf 'LYQUID_ID=%q\n' "$LYQUID_ID"
        printf 'MODE=%q\n' "$MODE"
        printf 'LOCALNET_DIR=%q\n' "$LOCALNET_DIR"
        printf 'SERVE_URL=%q\n' "$SERVE_URL"
        printf 'VITE_URL=%q\n' "$VITE_URL"
        printf 'STARTED_AT=%q\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    } > "$STATE_FILE"
}

load_state() {
    [[ -f "$STATE_FILE" ]] || return 1
    # The file is generated by write_state and contains shell-escaped scalar values only.
    # shellcheck disable=SC1090
    source "$STATE_FILE"
}

pid_is_live() {
    local pid="$1"
    [[ -n "$pid" ]] && kill -0 "$pid" >/dev/null 2>&1
}

group_is_live() {
    local pid="$1"
    [[ -n "$pid" ]] && kill -0 -- "-$pid" >/dev/null 2>&1
}

session_is_live() {
    load_state || return 1
    group_is_live "${LOCALNET_PID:-}" || pid_is_live "${SERVE_PID:-}" || pid_is_live "${VITE_PID:-}"
}

ensure_no_active_session() {
    if session_is_live; then
        echo "A Price Feed session is already running. Use scripts/run.sh status or scripts/run.sh stop." >&2
        exit 1
    fi
    if [[ -f "$STATE_FILE" ]]; then
        echo "Removing stale Price Feed session state."
        rm -f "$STATE_FILE"
    fi
}

ensure_port_free() {
    local port="$1"
    local label="$2"
    if lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
        echo "$label port $port is already in use. Stop its owner before starting this demo." >&2
        exit 1
    fi
}

wait_for_http() {
    local url="$1"
    local pid="$2"
    local label="$3"
    local deadline=$((SECONDS + 30))

    while ! curl --silent --fail --output /dev/null "$url"; do
        pid_is_live "$pid" || { echo "$label exited before becoming ready." >&2; return 1; }
        ((SECONDS < deadline)) || { echo "$label did not become ready at $url." >&2; return 1; }
        sleep 1
    done
}

wait_for_exit() {
    local pid="$1"
    local is_group="$2"
    local deadline=$((SECONDS + 10))

    while :; do
        if [[ "$is_group" == 1 ]]; then
            group_is_live "$pid" || return 0
        else
            pid_is_live "$pid" || return 0
        fi
        ((SECONDS < deadline)) || return 1
        sleep 1
    done
}

stop_recorded_process() {
    local label="$1"
    local pid="$2"
    local is_group="$3"
    local force="$4"

    if [[ "$is_group" == 1 ]]; then
        group_is_live "$pid" || return 0
    else
        pid_is_live "$pid" || return 0
    fi

    echo "Stopping $label."
    if [[ "$is_group" == 1 ]]; then
        kill -TERM -- "-$pid" >/dev/null 2>&1 || true
    else
        kill -TERM "$pid" >/dev/null 2>&1 || true
    fi

    if wait_for_exit "$pid" "$is_group"; then
        return 0
    fi
    if [[ "$force" != 1 ]]; then
        echo "$label did not stop; rerun with stop --force." >&2
        return 1
    fi

    echo "Force stopping $label."
    if [[ "$is_group" == 1 ]]; then
        kill -KILL -- "-$pid" >/dev/null 2>&1 || true
    else
        kill -KILL "$pid" >/dev/null 2>&1 || true
    fi
    wait_for_exit "$pid" "$is_group"
}

stop_session() {
    local clean="$1"
    local force="$2"
    local result=0

    if ! load_state; then
        echo "No recorded Price Feed session."
        [[ "$clean" == 1 ]] && rm -rf "$RUN_DIR"
        return 0
    fi

    stop_recorded_process "Vite" "${VITE_PID:-}" 0 "$force" || result=1
    stop_recorded_process "hosted UI proxy" "${SERVE_PID:-}" 0 "$force" || result=1
    stop_recorded_process "localnet" "${LOCALNET_PID:-}" 1 "$force" || result=1

    if [[ "$result" == 0 ]]; then
        rm -f "$STATE_FILE"
        if [[ "$clean" == 1 ]]; then
            echo "Removing Price Feed runtime data."
            rm -rf "$RUN_DIR"
        fi
    fi
    return "$result"
}

clean_artifacts() {
    if session_is_live; then
        echo "A Price Feed session is running. Stop it before removing build artifacts." >&2
        return 1
    fi

    echo "Removing Price Feed build artifacts."
    rm -rf "$EXAMPLE_DIR/lyquid_tools_target" "$EXAMPLE_DIR/assets"
}

show_status() {
    if ! load_state; then
        echo "Price Feed is not running."
        return 0
    fi

    echo "Price Feed session"
    printf '  Mode: %s\n' "${MODE:-unknown}"
    printf '  Lyquid: %s\n' "${LYQUID_ID:-unknown}"
    printf '  Localnet: %s (pid %s)\n' "$(group_is_live "${LOCALNET_PID:-}" && echo running || echo stopped)" "${LOCALNET_PID:-none}"
    printf '  Hosted proxy: %s (pid %s, %s)\n' "$(pid_is_live "${SERVE_PID:-}" && echo running || echo stopped)" "${SERVE_PID:-none}" "${SERVE_URL:-$SERVE_URL}"
    printf '  Vite: %s (pid %s, %s)\n' "$(pid_is_live "${VITE_PID:-}" && echo running || echo stopped)" "${VITE_PID:-none}" "${VITE_URL:-$VITE_URL}"
}

on_exit() {
    local status=$?
    trap - EXIT INT TERM
    stop_session 0 0 || true
    exit "$status"
}

open_url() {
    local url="$1"
    echo "Opening $url"
    open "$url" || echo "Open this URL in a browser: $url"
}

prepare_runtime() {
    ensure_no_active_session
    mkdir -p "$LOCALNET_DIR"
    export LOCALNET_WORK_DIR="$LOCALNET_DIR"
    # shellcheck source-path=SCRIPTDIR
    source "$EXAMPLE_DIR/../scripts/lib/demo.sh"
}

build_for_mode() {
    "$SCRIPT_DIR/build.sh"
}

bootstrap_demo() {
    demo_start_localnet multi
    LOCALNET_PID="$DEMO_LOCALNET_PID"
    write_state
    trap on_exit EXIT
    trap 'exit 130' INT TERM

    demo_deploy "price-feed" "$EXAMPLE_DIR/Cargo.toml"
    LYQUID_ID="$LYQUID_ID"
    write_state
    demo_wait_for_lyquid "get_node_ids() returns (string[])"

    echo "Staging the Price Feed oracle committee."
    demo_send "configure_committee(bytes32[])" "$(demo_node_ids_array)"
    demo_activate_oracle "price_feed"
    demo_wait_for_committee 4

    local sources=(binance binance coinbase coinbase)
    local index
    for index in 0 1 2 3; do
        demo_expect_true \
            "$(demo_call_at "${DEMO_NODE_WS[$index]}" "set_price_source(string) returns (bool)" "${sources[$index]}")" \
            "set_price_source on node $((index + 1))"
    done

    echo "Starting continuous market price reporting every 10 seconds."
    demo_expect_true "$(demo_call "start_reporting(uint64) returns (bool)" 10000)" "start_reporting"
}

start_hosted_proxy() {
    ensure_port_free 8080 "Hosted UI proxy"
    echo "Starting hosted UI proxy at $SERVE_URL"
    "${SHAKER[@]}" serve "$LYQUID_ID" --endpoint "$DEMO_PRIMARY_WS" --listen "$SERVE_ADDR" > "$RUN_DIR/shaker-serve.log" 2>&1 &
    SERVE_PID=$!
    write_state
    wait_for_http "$SERVE_URL/lyquid/info" "$SERVE_PID" "Hosted UI proxy"
}

start_vite() {
    ensure_port_free 5173 "Vite"
    echo "Starting Vite at $VITE_URL"
    VITE_PRICE_FEED_HOSTED_ORIGIN="$SERVE_URL" \
        pnpm --dir "$EXAMPLE_DIR/ui" dev -- --host 127.0.0.1 --port 5173 --strictPort > "$RUN_DIR/vite.log" 2>&1 &
    VITE_PID=$!
    write_state
    wait_for_http "$VITE_URL" "$VITE_PID" "Vite"
}

run_mode() {
    resolve_shaker
    prepare_runtime
    build_for_mode
    bootstrap_demo

    case "$MODE" in
        hosted)
            start_hosted_proxy
            open_url "$SERVE_URL"
            echo "Hosted UI is running. Press Ctrl-C to stop the demo."
            wait "$SERVE_PID"
            ;;
        dev)
            start_hosted_proxy
            start_vite
            open_url "$VITE_URL"
            echo "Vite is running. Press Ctrl-C to stop the demo."
            wait "$VITE_PID"
            ;;
        console)
            echo "Opening Shaker console. Press Ctrl-C to stop the demo."
            "${SHAKER[@]}" console "$LYQUID_ID" --endpoint "$DEMO_PRIMARY_WS"
            ;;
    esac
}

choose_mode() {
    cat <<'EOF'
Price Feed demo
  1) Build, deploy, and open hosted UI
  2) Deploy and start Vite development UI
  3) Build, deploy, and open Shaker console
  4) Stop and completely clean the Price Feed demo
  q) Quit
EOF
    read -r -p "Select [1]: " selection
    case "${selection:-1}" in
        1) MODE=hosted ;;
        2) MODE=dev ;;
        3) MODE=console ;;
        4)
            stop_session 1 1
            clean_artifacts
            exit 0
            ;;
        q|Q) exit 0 ;;
        *) echo "Unknown selection: $selection" >&2; exit 2 ;;
    esac
}

main() {
    case "${1:-}" in
        "") choose_mode ;;
        --hosted) MODE=hosted ;;
        --dev) MODE=dev ;;
        --console) MODE=console ;;
        status)
            show_status
            return
            ;;
        stop)
            local clean=0
            local force=0
            shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --clean) clean=1 ;;
                    --force) force=1 ;;
                    *) usage >&2; exit 2 ;;
                esac
                shift
            done
            stop_session "$clean" "$force"
            return
            ;;
        clean)
            shift
            if [[ $# -ne 1 || "$1" != "--artifacts" ]]; then
                usage >&2
                exit 2
            fi
            clean_artifacts
            return
            ;;
        -h|--help) usage; return ;;
        *) usage >&2; exit 2 ;;
    esac
    run_mode
}

main "$@"
