[package]
name = "basicswap"
workspace = "../.."
publish = false
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lyquid = { workspace = true, features = ["ldk"] }

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true
